// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83p1zFDGxJDUyFuEiJP2XHs8N4Yjunhw',
    appId: '1:1045469308321:web:4234503a9e87fed65dd7e0',
    messagingSenderId: '1045469308321',
    projectId: 'wanderlust-a42cd',
    authDomain: 'wanderlust-a42cd.firebaseapp.com',
    storageBucket: 'wanderlust-a42cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOGcwbeR7oNX4r6bGJoGF8QJVozKdfCog',
    appId: '1:1045469308321:android:6cd691bd15da1b9a5dd7e0',
    messagingSenderId: '1045469308321',
    projectId: 'wanderlust-a42cd',
    storageBucket: 'wanderlust-a42cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgPWBNWAawoHjJOnAd4N0pM9oYWeCYR8',
    appId: '1:1045469308321:ios:50a9dc5c2ef7eef25dd7e0',
    messagingSenderId: '1045469308321',
    projectId: 'wanderlust-a42cd',
    storageBucket: 'wanderlust-a42cd.appspot.com',
    iosClientId:
        '1045469308321-1quct3t8arlobc923lfaja0niq5me6ir.apps.googleusercontent.com',
    iosBundleId: 'com.wanderlust.admin',
  );
}
